name: PyTest self-hosted

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  simple_pytest:
    name: Run pytest on self-hosted
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          name: PTB-MR/mrpro
          ref: refs/heads/main
      - name: Show nvidia-smi results
        run: |
          nvidia-smi

      - name: Install MRpro and Dependencies
        run: pip install --upgrade --upgrade-strategy eager .[test]

      - name: Run PyTest and Generate Coverage Report
        run: |
          (set -o pipefail && pytest -n 4 -m "cuda" --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered --cov=mrpro | tee pytest-coverage.txt)
        shell: bash

      - name: Upload PyTest Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-selfhosted
          path: |
            pytest-coverage.txt
            pytest.xml
          overwrite: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true
