name: Coverage Report

on:
  workflow_run:
    workflows:
      - PyTest
    types:
      - completed

permissions:
  actions: read
  pull-requests: write

jobs:
  coverage_report:
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      # download artifacts from the test job in the pytest.yml workflow
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: pytest-report

      - name: 'Get PR context'
        id: pr-context
        env:
          # Token required for GH CLI:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Best practice for scripts is to reference via ENV at runtime. Avoid using the expression syntax in the script content directly:
          PR_TARGET_REPO: ${{ github.repository }}
          # If the PR is from a fork, prefix it with `<owner-login>:`, otherwise only the PR branch name is relevant:
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
        # Query the PR number by repo + branch, then assign to step output:
        run: |
          gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
              --json 'number' --jq '"number=\(.number)"' \
              >> "${GITHUB_OUTPUT}"
        

      # pytest_metadata is set in pytest.yml as A=value\nB=value\n...
      - name: Set vars from pytest_metadata
        run: |
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done < pytest_metadata
      - name: Show parent workflow info
        run: |
          echo ${{ github.event.workflow_run.event }} \
          echo ${{ github.event.workflow_run.event.pull_request }} \
          echo ${{ github.event.workflow_run.event.pull_request.number }} \
          echo ${{ steps.pr-context.outputs.number }} \
          echo ${{ github.event.workflow_run.head_branch }} \
          echo ${{ env.pr-number }}

      - name: Post PyTest Coverage Comment
        id: coverage_comment
        uses: MishaKav/pytest-coverage-comment@v1.1.53
        with:
          issue-number: ${{ env.pr-number }}
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml

      - name: Post Failure Comment if Coverage Comment failed
        # if there is no data the comment action does not fail
        # but has an empty output
        if: steps.coverage_comment.outputs.coverageHtml == ''
        uses: edumserrano/find-create-or-update-comment@v3
        with:
          issue-number: ${{ env.pr-number }}
          # see https://github.com/MishaKav/pytest-coverage-comment/blob/81882822c5b22af01f91bd3eacb1cefb6ad73dc2/src/index.js#L97
          # for the generation of the unique id for comment
          # in this particular case, there is no additional watermarkUniqueId
          body-includes: '<!-- Pytest Coverage Comment: ${{ github.job }} -->'
          comment-author: 'github-actions[bot]'
          body: |
            <!-- Pytest Coverage Comment: ${{ github.job }} -->
            ### :x: PyTest Coverage Report was not found.

            Check the PyTest Workflow.
          edit-mode: replace

      # - name: Create Coverage Badge on Main Branch Push
      #   uses: schneegans/dynamic-badges-action@v1.7.0
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   with:
      #     auth: ${{ secrets.GIST_SECRET }}
      #     gistID: 48e334a10caf60e6708d7c712e56d241
      #     filename: coverage.json
      #     label: Coverage Report
      #     message: ${{ steps.coverageComment.outputs.coverage }}
      #     color: ${{ steps.coverageComment.outputs.color }}
      #     namedLogo: python

      # - name: Set Pipeline Status Based on Test Results
      #   if: steps.coverageComment.outputs.errors != 0 || steps.coverageComment.outputs.failures != 0
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       core.setFailed("PyTest workflow failed with ${{ steps.coverageComment.outputs.errors }} errors and ${{ steps.coverageComment.outputs.failures }} failures.")
