name: Workflow from 

on:
  workflow_run:
    workflows:
      - Comment triggered
    types:
      - completed

permissions:
  actions: read
  pull-requests: write

jobs:
  print_parent_event_type:
    name: Print parent event 
    runs-on: ubuntu-latest
    steps:
      - name: Set the artifact name
        run: |
          echo "${{ github.event.workflow_run.event }}"
      - name: Dump event context
        env:
          GITHUB_EVENT: ${{ toJson(github.event.workflow_run) }}
        run: echo "$GITHUB_EVENT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get PR number for the pull_request trigger
        id: pr-context
        env:
          # Token required for GH CLI:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Best practice for scripts is to reference via ENV at runtime. Avoid using the expression syntax in the script content directly:
          PR_TARGET_REPO: ${{ github.repository }}
          # If the PR is from a fork, prefix it with `<owner-login>:`, otherwise only the PR branch name is relevant:
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
        run: |
          gh pr view --repo "${PR_TARGET_REPO}" "${PR_BRANCH}" \
              --json 'number' --jq '"number=\(.number)"' \
              >> "${GITHUB_OUTPUT}"
      - name: Echo pr-context
        run: |
          echo "${{ steps.pr-context.outputs.number }}"
      - name: Test output parsing
        id: io-io-yo
        run: |
         echo "is_pr=${{ 2 == 2 }}" >> $GITHUB_OUTPUT
      - name: Expression results
        if: ${{ steps.io-io-yo.outputs.is_pr }}
        run: "echo ${{ steps.io-io-yo.outputs.is_pr }}"
      - name: Also test
        if: ${{ !(!steps.io-io-yo.outputs.is_pr) }}
        run: "echo ${{ !steps.io-io-yo.outputs.is_pr }}"
